BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Seat] DROP CONSTRAINT [Seat_status_df];
ALTER TABLE [dbo].[Seat] ALTER COLUMN [status] NVARCHAR(1000) NOT NULL;
ALTER TABLE [dbo].[Seat] ADD [isBooked] BIT NOT NULL CONSTRAINT [Seat_isBooked_df] DEFAULT 0;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
